export const listAeroport =[
    {
      id: 1,
      Pays: "France", 
      Ville: "Nice",
      NomAeroport: "Côte d'Azur", 
      CodeIATA: "NCE",
    },    
    {
      id: 2,
      Pays: "France", 
      Ville: "Lyon",
      NomAeroport: "Lyon-Saint Exupéry", 
      CodeIATA: "LYS",
    },    
    {
      id: 3,
      Pays: "France", 
      Ville: "Paris",
      NomAeroport: "Paris Charles-de-Gaulle", 
      CodeIATA: "CDG",
    },    
    {
      id: 4,
      Pays: "France", 
      Ville: "Paris",
      NomAeroport: "Paris Orly", 
      CodeIATA: "ORY",
    },    
    {
      id: 5,
      Pays: "Pays-Bas", 
      Ville: "Amsterdam",
      NomAeroport: "Amsterdam-Schiphol", 
      CodeIATA: "AMS",
    },    
    {
      id: 6,
      Pays: "Grande Bretagne", 
      Ville: "Londres",
      NomAeroport: "Londres Heathrow", 
      CodeIATA: "LHR",
    },    
    {
      id: 7,
      Pays: "Grèce", 
      Ville: "Athènes",
      NomAeroport: "Athènes International", 
      CodeIATA: "ATH",
    },    
    {
      id: 8,
      Pays: "Grèce", 
      Ville: "Crète",
      NomAeroport: "La Canée", 
      CodeIATA: "CHQ",
    },    
    {
      id: 9,
      Pays: "Madagascar", 
      Ville: "Antananarivo",
      NomAeroport: "Antananarivo", 
      CodeIATA: "TNR",
    },    
    {
      id: 10,
      Pays: "Canada", 
      Ville: "Québec",
      NomAeroport: "Ville de Québec", 
      CodeIATA: "YQB",
    },
   
  ];